# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-09-07 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growabeard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
        migrations.AddField(
            model_name='campaign',
            name='title',
            field=models.CharField(default='SI', max_length=255),
            preserve_default=False,
        ),
    ]
