# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('growabeard', '0002_auto_20160906_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_token', models.CharField(max_length=255)),
                ('twitter_secret', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='campaignentry',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='growabeard.Campaign'),
        ),
        migrations.AlterField(
            model_name='campaignentry',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='campaignentry',
            name='file',
            field=models.ImageField(upload_to=b''),
        ),
    ]
